version: "3"
services:
  db:
    image: "postgres:17.8"
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=PzBYnzHRq8afwfBrmF3i6kQd
      - POSTGRES_DB=testing
    ports:
      - "5432:5432"
